### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AstraeaZero** [Kaplas80/TranslationFramework2#7] opened 2019-12-17 14:51 UTC
Hey, i founded your post on Zenhax, but i can't registrate my account. we want to translate the game from English to Polish, unfortunately an error occurs when selecting a folder. 
Procesando media...
Buscando .\Yakuza0.exe...
1 ficheros encontrados y añadidos
Procesando media\data\2dpar\sprite_c.par...
ERROR: Odmowa dostępu do ścieżki „G:\YakuzaPL\containers\ae62a2a7-4a55-4277-96cb-69f1b50edfe9”.
   w System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   w System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   w System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   w System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   w YakuzaGame.Files.ParFile.Dump(ExtendedBinaryReader input, ParFolderInfo folder, String parentFolder, String logFile)
   w YakuzaGame.Files.ParFile.Dump(String inputPath, String outputFolder)
   w YakuzaGame.Files.ParFile.Extract(String inputPath, String outputFolder)
   w YakuzaGame.Game.ExtractFile(String inputFile, String outputPath)
   w TF.Core.TranslationProject.UpdateTranslationFiles(TranslationProject project, BackgroundWorker worker)
   w TF.GUI.MainForm.<>c__DisplayClass4_0.<CreateNewTranslation>b__0(Object sender, DoWorkEventArgs args)

I notice this:
ERROR: Odmowa dostępu do ścieżki „G:\YakuzaPL\containers\ae62a2a7-4a55-4277-96cb-69f1b50edfe9”.
In English: Cannot access to path.

Idk why but when i create new project, this folder will be automatickly blocked.

Thanks for your time
![image](https://user-images.githubusercontent.com/44085780/71006525-b7b65180-20e5-11ea-8ae6-05f580840be4.png)

**Comment by Kaplas80** [comment] 2019-12-17 15:05
Hi!

It's the first time I see that error with the app. Do you have enough free space in G:? You need more than 8GB free because the app extracts the game files in `container` folder.

I've just tried to create a new project and it works for me. Can you try to create it in another drive?

**Comment by AstraeaZero** [comment] 2019-12-17 15:44
Yes, on all HDD's i have this same error, at this moment i can only translate a Yakuza0.exe
Thanks for fast reply
One time i get similar problem with other guy who making a Osu2Saber app, he fixed it with coding a automatic region changes to code, for example, some Countries using comma or period. This is how he fixed error. Maybe in this point?
![image](https://user-images.githubusercontent.com/44085780/71010437-1bdc1400-20ec-11ea-8e0f-547cc1641226.png)

**Comment by Kaplas80** [comment] 2019-12-17 16:03
I don't think it is related with region, the code that throws the error just extracts the .par file contents in `containers` folder. It looks like a user permission problem. Can you run the app as Administrator?

Changing the font for the game needs 3 steps:
1. Replace `hd_hankaku.dds` in `font.par`.
2. Fix character spacing in `Yakuza0.exe`. The app can auto adjust the character spacing loading the new font dds in "Fuente" tab when selecting the .exe. Just click on "Cargar Fuente Nueva" button and then click on "Auto ajustar".
![FontScreen](https://user-images.githubusercontent.com/5345429/71012087-d53be900-20ee-11ea-84e0-5eef728ae801.png)
3. Enable "Usar codificación ISO-8859-1" in "Parches" tab.

**Comment by AstraeaZero** [comment] 2019-12-17 16:11
Yes, run as administrator doesn't work, created new project on drive C:

**Comment by AstraeaZero** [comment] 2019-12-17 16:11
Yes, run as administrator doesn't work, created new project on drive C:

This same

**Comment by Kaplas80** [comment] 2019-12-17 16:29
I'm not able to reproduce the issue. Can you record and upload a video creating a new project so I can see exactly what you are doing?

**Comment by AstraeaZero** [comment] 2019-12-17 16:36
I just making a new project on any driver, first selecting a Yakuza 0 game, next i pointed a folder for project and at last selecting a folder with game.
i have everyting like this C: D: G:\YakuzaPL
and game instalation folder: D:\Gry\Steam\steamapps\common\Yakuza 0
This is all, im using a Administrator Account
![image](https://user-images.githubusercontent.com/44085780/71015246-8b093680-20f3-11ea-873d-b719dff0a008.png)
All permissions are allow to read/write. Idk why after creating New project and clicking accept, this folder being Only for Read. Give me a sec.

**Comment by Kaplas80** [comment] 2019-12-17 16:51
The "square" in "Read Only" check doesn't means that the folder is read only. It means that it's "undefined". If you create a new folder manually in explorer it will have the same square.

Can you download and test this? https://we.tl/t-5cuB7Z6fxE

**Comment by AstraeaZero** [comment] 2019-12-17 17:25
Procesando media...
Buscando .\Yakuza0.exe...
1 ficheros encontrados y añadidos
Procesando media\data\2dpar\sprite_c.par...
ERROR: Odmowa dostępu do ścieżki „C:\PL\containers\78c3beb5-7c25-42cf-8fcf-9996b0fdbae0”.
   w System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   w System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   w System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   w System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   w YakuzaGame.Files.ParFile.Dump(ExtendedBinaryReader input, ParFolderInfo folder, String parentFolder, String logFile)
   w YakuzaGame.Files.ParFile.Dump(String inputPath, String outputFolder)
   w YakuzaGame.Files.ParFile.Extract(String inputPath, String outputFolder)
   w YakuzaGame.Game.ExtractFile(String inputFile, String outputPath)
   w TF.Core.TranslationProject.UpdateTranslationFiles(TranslationProject project, BackgroundWorker worker)
   w TF.GUI.MainForm.<>c__DisplayClass4_0.<CreateNewTranslation>b__0(Object sender, DoWorkEventArgs args)

**Comment by Kaplas80** [comment] 2019-12-17 17:41
I don't know why it's throwing that error... it works for me and no one has reported this error before. I still think that it is some kind of user permission problem.

**Comment by AstraeaZero** [comment] 2019-12-17 17:56
I tryed to use Gibbed Yakuza, from other github and i have this same
![image](https://user-images.githubusercontent.com/44085780/71021540-e4c32e00-20fe-11ea-9496-f3489327113c.png)
Maybe there is a problem?
****

**Comment by Kaplas80** [comment] 2019-12-17 18:06
In the administrator command line you are missing the quotes in file name

**Comment by AstraeaZero** [comment] 2019-12-17 18:18
Ok my fault: Yep this same here...
![image](https://user-images.githubusercontent.com/44085780/71022913-ed693380-2101-11ea-9f85-8c5b2b81ca91.png)

**Comment by Kaplas80** [comment] 2019-12-17 18:26
Try to copy `sprite_c.par` to the desktop and run Gibbed tool.

**Comment by AstraeaZero** [comment] 2019-12-17 18:31
Yep: With error but unpacked
![image](https://user-images.githubusercontent.com/44085780/71023793-c3b10c00-2103-11ea-859d-e8d5d1af1b77.png)

**Comment by AstraeaZero** [comment] 2019-12-17 18:38
Read up

**Comment by Kaplas80** [comment] 2019-12-17 18:54
Don't worry! I'm closing the issue. If you have another error, open a new one.

**Closed by Kaplas80** 2019-12-17 18:54 UTC
